### ISSUE TITLE
Lack of Elasticsearch documentation

### ISSUE THREAD

**Issue by rdingwell** [dfci/matchminer#3]
There is a lack of information regarding how to setup Elasticsearch and the mongo-connector for use with the Matchminer set of tools.   Notably missing is the versions of ES that are supported, any associated indexing schemas as well as commands for syncing mongo and ES. 

Attempting to run a mongo-connector command to sync the 2 systems yielded errors in the log file for multiple type mappings for particular keys.  This leads me to believe that a ES version of 5 or less is required as multiple type mappings are no longer supported in ES 6 and greater. 

I understand that this may be provided in the docker images but we are attempting to evaluate building additional functionality into matchminer and need to set this up in a developer instance which is proving difficult with missing documentation.

**Comment by ethansiegl** [comment]
Hello. Yes you are correct that an elasticsearch version of 5 or earlier is required for the application to function correctly. 

You are also correct that there are mappings, settings and analyzers required to load if you are using a vanilla elasticsearch instance. I can provide you here with links to some of the mapping, analyzer, and analysis files you need here, as well as a bash script you can use to load the files into the ES instance. You will also need to setup a local elasticsearch instance which uses a custom synonym file. 

For reference, the docker container which has all of these settings, mappings, synonyms, and other configurations pre-loaded can be accessed [here].(https://hub.docker.com/r/matchminer/mmelastic)

**Elasticsearch Setup**
[mapping.json](https://gist.github.com/ethansiegl/2e56b9a9128e4aae03b59dbf2bd167d3)
[analyzers.json](https://gist.github.com/ethansiegl/4bb50b8073d51d74edf7bfc42ad61ee4)
[analysis.json](https://gist.github.com/ethansiegl/f1d9f164e444dd30affeaf9a5bd0208c)
[synonyms.txt](https://gist.github.com/ethansiegl/cf20bffc043d41c0618ab39fec1ab30e)
[elasticsearch.yml](https://gist.github.com/ethansiegl/5dbbb9937120e3153c2795c56b2c807c)
[elasticsearch_setup.sh](https://gist.github.com/ethansiegl/9dd5faa590b06820b8b1abb402b0d710)

Once you have downloaded all of the files, first startup an elasticsearch instance in a custom network. You will need to update some directory paths. Here is a compose file for reference:

`docker network create mm_custom_network`

```
version: '3'
services:

  elastic:
    container_name: prod_elastic
    restart: "no"
    image: elasticsearch:2.4.0
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
      - /data/es_volume/data:/usr/share/elasticsearch/data    #update directory
      - /data/matchminer/staging/elastic/backup:/backup      #update directory 
    networks:
      - mm_custom_network
```

`docker-compose up -d elastic`

Then run the bash script:
`./elasticsearch_setup.sh`

Let me know if this helps. I will try and find some time to add this to the documentation
